apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: pifrost
  name: pifrost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pifrost
  name: pifrost-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pifrost-reader
  namespace: pifrost
subjects:
- kind: ServiceAccount
  name: pifrost
roleRef:
  kind: Role
  name: pifrost-reader
  apiGroup: rbac.authorization.k8s.io
